create table CARDAPIO(
CODIGO INT auto_increment,
DESCRICAO VARCHAR (255),
PRECO DECIMAL (7,2),
primary key (CODIGO)
);

create table CLIENTE(
CODIGO INT auto_increment,
NOME VARCHAR (255),
TELEFONE VARCHAR (255),
ENDERECO VARCHAR (255),
primary key (CODIGO)
);

create table ENTREGADORES(
CODIGO INT auto_increment,
NOME VARCHAR (255),
TELEFONE VARCHAR (255),
primary key (CODIGO)
);

create table STATUS(
CODIGO INT auto_increment,
DESCRICAO VARCHAR (255),
primary key (CODIGO)
);
create table PEDIDO(
CODIGO INT auto_increment,
CLIENTE INT,
ENTREGADOR INT,
STATUS INT,
primary key (CODIGO),
CONSTRAINT FK_CLIENTE FOREIGN KEY (CLIENTE)
    REFERENCES CLIENTE(CODIGO),
    CONSTRAINT FK_ENTREGADOR FOREIGN KEY (ENTREGADOR)
    REFERENCES ENTREGADORES(CODIGO),
    CONSTRAINT FK_STATUS FOREIGN KEY (STATUS)
    REFERENCES STATUS(CODIGO)
);
create table ITENS_PEDIDO(
ID INT auto_increment,
CODIGO_PEDIDO INT,
CODIGO_ITEM INT,
QUANTIDADE INT,
primary key (ID),
CONSTRAINT FK_CODIGO_PEDIDO FOREIGN KEY (CODIGO_PEDIDO)
    REFERENCES PEDIDO(CODIGO),
    CONSTRAINT FK_CODIGO_ITEM FOREIGN KEY (CODIGO_ITEM)
    REFERENCES CARDAPIO(CODIGO)
    );
insert into ENTREGADORES (NOME,TELEFONE) values ('JOÃO', '4198764567');
insert into ENTREGADORES (NOME,TELEFONE) values ('JOSE', '4198778549');
insert into STATUS (DESCRICAO) values ('2 - ENTREGUE');

INSERT INTO sanduiche.cliente (NOME, TELEFONE, ENDERECO) VALUES('LEONARDO', '4187659999', 'RUA FULANO 12');
INSERT INTO sanduiche.pedido (CLIENTE, ENTREGADOR, STATUS) VALUES(1, 1, 3);

ALTER TABLE `PEDIDO` ADD CONSTRAINT `FK_STATUS` FOREIGN KEY ( `STATUS` ) REFERENCES `STATUS` ( `CODIGO` ) ;
insert into ITENS_PEDIDO (CODIGO_PEDIDO, CODIGO_ITEM, QUANTIDADE) values (1,1,4);

select * from pedido where STATUS=1 and CLIENTE = 1;
select * from ITENS_PEDIDO inner join PEDIDO on ITENS_PEDIDO.CODIGO_PEDIDO = PEDIDO.CODIGO where PEDIDO.STATUS = 1;

